environment:
  matrix:
    - nodejs_version: '7'
platform:
  - x86
  - x64
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
matrix:
  fast_finish: true
build: off
