environment:
  matrix:
    - nodejs_version: '7'
    - nodejs_version: '8'
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
matrix:
  fast_finish: true
build: off
